### ISSUE TITLE
Handling Missing Data

### ISSUE THREAD

**Issue by mattjones315** [Kalhor-Lab/QFM#1]
Hello,

Thank you so much for publishing this method! I'm excited to try it out on our data and have two questions.

First, how do you recommend handling missing data? Specifically, we work with lineage-tracing data that contains a fair amount of missing data in the character matrices that are used to reconstruct trees. This missing data can come from the stochasticity of detecting transcript from the single-cell sequencing platform or from the heritable silencing of the tracing barcodes. We normally encode these missing data specifically within our character matrices.

Second, how do you parameterize the "total_time" of the tree. Do you have a way of estimating this for a given input? How sensitive is reconstruction to this parameter? How do you recommend handling cases where you are not sure what the total time is of a given lineage?

Thank you so much in advance for your help!

Best,
Matt

**Comment by mattjones315** [comment]
Hello @wefang and @asapirstein ,

I'm following up here because I'd love to use this package with our data, any chance you could give me some pointers on how to handle missing data and set some of the hyperparameters like total time?

Thanks in advance again!

-Matt

**Comment by asapirstein** [comment]
Hi @mattjones315, 
Sorry for the sluggish response on our end - here is the basic paradigm that we are using.
## Missing Sites ## 
Suppose you have *n* missing sites in the data, order the missing sites from the least absent to the most absent. Begining with the least absent, lets call this site *s1* , we impute the most likely allele for each site, using `xgboost`. @wefang  is working on a tutorial,  but in the mean time, there is a section in the preprint - *Imputation of missing hgRNA alleles with xgboost* - in Methods that has some details. Let us know if you still have questions!

## Estimating `total_time` ## 
`total_time` is just the duration, in days, before sampling that the barcode element was active for. There are two scenarios that come to mind: 

1. The barcode element was turned on upon fertilization, then `total_time` corresponds to embryonic time. Ie, if you sampled at E15, then `total_time` would be 15
1. The barcode element was turned on, via something like dox induction. Then `total_time` would be the window of time from induction to sampling. 
    So suppose that you induced dox on E4, and sampled at E15, then `total_time` would be 11. 

Let me know if there are further questions, I suspect that I did not full answer the hyperparameter questions. 
-A

**Comment by mattjones315** [comment]
Hi @asapirstein ,

Thanks so much for the clarifications here. I recall reading about the missing data imputation in your manuscript - this is a cool idea! - but I'm not exactly sure how the XGBoost model is used in practice here, so I'll just wait for the tutorial. Thank you in advance to you and the rest of the team.

Regarding the `total_time` parameter - it seems that this is in terms of total _days_ -- but does this really matter? For example, if you assume the tree is scaled to a length of 1, I presume that edge lengths will be proportional this scaling? 

Thank you again for your help here!

-Matt

**Comment by wefang** [comment]
Hey @mattjones315 ,
Thanks for raising the issue, and apologies for the delay. I will add the tutorial on missing allele imputation this weekend, and you're right about the `total_time`. It is required because we are interested in the absolute timing of events in the downstream pipeline, but if you're only applying Phylotime to get tree topology and relative branch length, it can be set to 1 or any other constant.

**Comment by wefang** [comment]
@mattjones315 ,
I've added a brief section to the end of vignette. [https://kalhor-lab.github.io/QFM/](url) Hopefully it will be helpful to you. There were some small updates, you may want to install again. Let me know if you have any feedback.

**Comment by mattjones315** [comment]
Hi @wefang ,

Thank you so much for your reply! I will try this out and will let you know if I run into any additional issues.

Thanks,
Matt
