### ISSUE TITLE
Inquiry about using a custom tree in the ice_fase_mod function of the phylotime package

### ISSUE THREAD

**Issue by kunwang34** [Kalhor-Lab/QFM#3]
Hello,

I have been exploring the phylotime package and its functionalities, particularly the `ice_fase_mod` function. I would like to inquire if it is possible to input a custom tree that I have built myself into the `ice_fase_mod` function instead of using the tree generated by the `phylotime` function.

I have already attempted to use my own tree as input for the `ice_fase_mod` function, but despite not encountering any errors, I did not receive any output results.

Could you please guide me on whether it is feasible to use a custom tree in the `ice_fase_mod` function and if there are any specific steps or considerations I need to take to make it work?

Thank you for your assistance. I'm looking forward to your response.

Best regards,
Kun

**Comment by wefang** [comment]
Hi Kun,
My apologies for the late response. It is possible to run `ice_fase_mod` with your own tree. The input to the function just needs to be a `phylo` object as defined by the `ape` package (you can read a newick file using the `read.tree` function from `ape`), and `sc_celltypes` needs to be a named character vector that maps the tip labels to some discrete cell types. I'm happy to help if you run into additional issues.
